name: WFCLib
description: An implementation the Wave Function Collapse algorithm.
version: 2.2.0
homepage: https://github.com/FarragoFiction/WFCLib
author: paradoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  collection: any

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: any
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git
